# Generated by Django 4.0.5 on 2022-07-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0009_posteo_delete_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='foto',
        ),
    ]
