# Generated by Django 4.0.5 on 2022-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0010_remove_posteo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
